### ISSUE TITLE
does not take vehicles

### ISSUE THREAD

**Issue by Matetv** [MaDHouSe79/mh-carlift#1]
Unfortunately, the lift does not take vehicles and the lift cannot be driven down again!!
https://i.ibb.co/tpcn9fF/20230210091801-1.jpg
https://i.ibb.co/Fhmj7Fs/20230210091825-1.jpg

https://i.ibb.co/VYLTW5T/20230210094343-1.jpg

	[5] = {		
		id        = 5,
		min       = 38.6,
		max       = 41.6,
		beforemax = 45.53,
		beforemin = 45.95,
		entity    = nil,
		needPoles = true,
		openMenu  = true,
		workarea  = {length = 7.0, wide = 7.0},
		job       = {"mechanic"},
		coords    = {["x"] = 936.85, ["y"] = -970.59, ["z"] = 38.5, ["h"] = 274.04},
	},

**Comment by MaDHouSe79** [comment]
then your lift is to far in the floor and the collider will stop working, make sure its a litte higher than this, also your Z axes are not the same.

**Comment by Matetv** [comment]
thx* for Infos! It worked!
